### ISSUE TITLE
Error: object 'nsIndex' not found from "EML Documentation" part

### ISSUE THREAD

**Issue by yvanlebras** [earnaud/R-EMD#17]
It seems that the last version I'm using present issue when trying to reach the content of a "deep node"

```
Listening on http://127.0.0.1:5046
Warning: Error in extractContent: object 'nsIndex' not found
  [No stack trace available]
```

![image](https://user-images.githubusercontent.com/7910679/59555699-b67d5e00-8fb6-11e9-9f8d-552ae51bd53b.png)

**Comment by yvanlebras** [comment]
Maybe just due to a transient issue....

**Comment by earnaud** [comment]
Error was due to the update which included namespaces referencing in the documentation module. 
In details: the documentation module relies on specific guideline (list of lists) file (contained in 'shinyApp/resources/docGuideline.RData') and an index of namespaces (contained in 'shinyApp/resources/nsIndex.RData'). It is this last file which missed the app. This error occurs when you try to access a doc part which partly relies on the nsIndex file.

**Comment by earnaud** [comment]
Last commit `correct patch 1` shall have corrected this.

**Comment by earnaud** [comment]
New error found: 
in `shinyApp/main.R` : object `nsIndex` was loaded from `resources/nsIndex.RData` under `ns.index` instead of `nsIndex` var name. Corrected in `correct-patch-2` (added new main.R).

**Comment by yvanlebras** [comment]
Again a related error
![image](https://user-images.githubusercontent.com/7910679/59755491-47d72380-9288-11e9-9559-dfa46a77913f.png)

**Comment by earnaud** [comment]
Please let me know if this issue still remains.

**Comment by yvanlebras** [comment]
It seems to be ok
